// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXHIIiwxC1VbUOArlIcWNJB5iJMuqnmsA',
    appId: '1:404130925737:web:91a917e5d555179b4c6db8',
    messagingSenderId: '404130925737',
    projectId: 'modelminds-325f9',
    authDomain: 'modelminds-325f9.firebaseapp.com',
    storageBucket: 'modelminds-325f9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ_pGk5rTO86R5ajZ3TC3Wncv92vLrToU',
    appId: '1:404130925737:android:a3d18986e19223f94c6db8',
    messagingSenderId: '404130925737',
    projectId: 'modelminds-325f9',
    storageBucket: 'modelminds-325f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwfKZd-GxRi1RxldW1OYqMU1lw4qPFrq4',
    appId: '1:404130925737:ios:cc84ca2f5f9abff44c6db8',
    messagingSenderId: '404130925737',
    projectId: 'modelminds-325f9',
    storageBucket: 'modelminds-325f9.firebasestorage.app',
    iosBundleId: 'com.example.ellm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwfKZd-GxRi1RxldW1OYqMU1lw4qPFrq4',
    appId: '1:404130925737:ios:cc84ca2f5f9abff44c6db8',
    messagingSenderId: '404130925737',
    projectId: 'modelminds-325f9',
    storageBucket: 'modelminds-325f9.firebasestorage.app',
    iosBundleId: 'com.example.ellm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXHIIiwxC1VbUOArlIcWNJB5iJMuqnmsA',
    appId: '1:404130925737:web:e3dc4e9dc7a1537e4c6db8',
    messagingSenderId: '404130925737',
    projectId: 'modelminds-325f9',
    authDomain: 'modelminds-325f9.firebaseapp.com',
    storageBucket: 'modelminds-325f9.firebasestorage.app',
  );
}
